name: Cleanup container registry
on:
  schedule:
    - cron:  '0 6 * * *'
  repository_dispatch:
    types: [cleanup]

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install werf CLI
        uses: werf/actions/install@v1.2

      - name: Cleanup
        env:
          WERF_SET_ENV_URL: "envUrl=https://www.company.org"
          WERF_REPO: "kiros/test-self-hosted"
        run: |
          source $(werf ci-env github --as-file)
          werf cleanup --repo $WERF_REPO
