name: Production Deployment
on:
  push:
    branches: [main]
jobs:

  converge:
    name: Converge
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install werf CLI
        uses: werf/actions/install@v1.2


      - name: Configure env
        env:
          WERF_SET_ENV_URL: "envUrl=https://www.company.org"
          WERF_REPO: "kiros/test-self-hosted"
        run: |
          source $(werf ci-env github --as-file)
          werf converge --env main --repo $WERF_REPO --set "global.git_branch=main,global.tier=test"
