name: Production Deployment
on:
  push:
    branches: [main]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure env
        run: |
          sh werf-ci-env.sh

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: production
        env:
          WERF_SET_ENV_URL: "envUrl=https://www.company.org"
