name: Production Deployment
on:
  push:
    branches: [main]
jobs:

  converge:
    name: Converge
    runs-on: registry.werf.io/werf/werf
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Configure env
        run: |
          bash werf-ci-env.sh
          env
          werf converge --repo $WERF_REPO

          #      - name: Converge
          #        uses: werf/actions/converge@v1.2
          #        with:
          #          env: production
          #        env:
          #          WERF_SET_ENV_URL: "envUrl=https://www.company.org"
          #          WERF_REPO: "kiros/test-self-hosted"
